### ISSUE TITLE
trusted by Google's Enhanced Safe Browsing

### ISSUE THREAD

**Issue by roycewilliams** [classvsoftware/under-new-management#2]
Creating this issue to track if/when the extension becomes trusted by Enhanced Safe Browsing, as per:

https://support.google.com/chrome_webstore/answer/2664769?visit_id=638454440143869860-549731240&rd=2#10745467&zippy=%2Cinstall-with-enhanced-safe-browsing

It appears that this process can take time, and even once the developer complies with the Chrome Web Store Developer Program Policies, the rest of the process is out of the developer's hands. So this issue is just to track / announce when the status changes.

**Comment by msfrisbie** [comment]
With ESB enabled, installing this extension from CWS doesn't give me any sort of warning that it's untrusted, so I'm going to close this issue with the assumption that it's now considered trusted.
