### ISSUE TITLE
Changelog text overflows with larger font sizes

### ISSUE THREAD

**Issue by rrrix** [classvsoftware/under-new-management#5]
Heyo!

I have my Chrome browser set to have some fairly large fonts, since I have a big monitor and use a very large resolution.

The extension currently shows up like this:

<img width="807" alt="Screenshot 2024-04-03 at 10 14 23 AM" src="https://github.com/classvsoftware/under-new-management/assets/3194704/6c93a313-caf9-49cf-b151-e0f87b76e256">

<img width="808" alt="Screenshot 2024-04-03 at 10 14 41 AM" src="https://github.com/classvsoftware/under-new-management/assets/3194704/66a9ab75-0aab-4b8f-9d51-9187a6c017b4">

It's not entirely unusable, but it's not ideal either...

In Chrome `chrome://settings/appearance` and `chrome://settings/fonts` I have my font sizes configured as follows:

| Settings Page | Name | Value |
|---------------|------|-------|
| chrome://settings/appearance | Font size | Very Large |
| chrome://settings/fonts | Font size | `24` <sup>†</sup> |
| chrome://settings/fonts | Minimum font size | `16` <sup>†</sup> | 

<sup>†</sup> There's no unit description, so I don't know if this is in points, pixels, picas, percents, millimeters, inches, fingers or toes.

<img width="686" alt="Screenshot 2024-04-03 at 10 16 18 AM" src="https://github.com/classvsoftware/under-new-management/assets/3194704/068ef3d0-4b36-4bd8-a68f-8fb552896dcd">

<img width="686" alt="Screenshot 2024-04-03 at 10 17 11 AM" src="https://github.com/classvsoftware/under-new-management/assets/3194704/6245e060-0f1b-4165-8f71-13ebecdaa791">

<img width="686" alt="Screenshot 2024-04-03 at 10 17 26 AM" src="https://github.com/classvsoftware/under-new-management/assets/3194704/3cf2a71e-2247-4b4a-9340-f44f084e1e14">

**Comment by msfrisbie** [comment]
Thanks for the report! I'll patch it so that all text wraps.
